github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: docker-compose -f run-without-collector.yaml --build pull
    command: docker-compose -f run-without-collector.yaml up -d

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  # Elasticsearch
  - port: 9200
  # Kibana
  - port: 5601
  # Hello app (use /hello endpoint)
  - port: 8888
  # Application performance monitoring (APM) server
  - port: 8200
  